name: Build and Sign Invisible Tracker

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    # Decodificamos la clave para que esté disponible como un archivo
    - name: Decode Keystore
      run: echo "${{ secrets.SIGNING_KEY_BASE64 }}" | base64 --decode > my-release-key.keystore

    # Usamos la ACCIÓN DE GRADLE (no ./gradlew) y le pasamos las variables de entorno
    - name: Build and Sign with Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.0'
        arguments: assembleRelease
      env:
        # Estas variables las leerá el archivo app/build.gradle
        SIGNING_STORE_FILE: ${{ github.workspace }}/my-release-key.keystore
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}

    # Subimos el APK firmado
    - name: Upload Signed APK
      uses: actions/upload-artifact@v4
      with:
        name: invisible-tracker-signed-apk
        # El archivo generado por gradle con esta configuración se llama app-release.apk
        path: app/build/outputs/apk/release/app-release.apk
        retention-days: 30
