# .github/workflows/build.yml (VERSIÓN DE DIAGNÓSTICO)

name: Diagnostic - List Files

on:
  push:
    branches: [ "main", "master" ]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show file and directory structure
        run: ls -R
