# .github/workflows/build.yml

name: Build Invisible Tracker

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Descarga el código del repositorio.
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Configura el entorno de Java (JDK 17).
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    # 3. Configura el SDK de Android. Esencial para licencias y herramientas.
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    # --- INICIO DE LA SOLUCIÓN CLAVE ---
    # 4. En lugar de usar ./gradlew (que no existe), usamos la acción oficial de Gradle.
    #    Esta acción lee tu archivo gradle/wrapper/gradle-wrapper.properties,
    #    descarga la versión correcta de Gradle y ejecuta el comando.
    - name: Build with Gradle Action
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: assembleRelease --stacktrace
    # --- FIN DE LA SOLUCIÓN CLAVE ---

    # 5. Sube el APK generado como un "artefacto" del build.
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: invisible-tracker-release-unsigned
        path: app/build/outputs/apk/release/app-release-unsigned.apk
        retention-days: 30
